[tool.poetry]
name = "ss-ana"
version = "1.1.0"
description = ""
authors = ["Nya-WSl <support@nya-wsl.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.10,<4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[[tool.poetry.source]]
name = "ustc"
url = "https://mirrors.ustc.edu.cn/pypi/simple"
priority = "primary"